FROM node:22-alpine
WORKDIR /app
COPY bot-school/package.json ./
RUN npm install
COPY bot-school/src ./src
COPY bot-school/tsconfig.json ./
RUN npm run build
EXPOSE 3002
CMD ["node", "dist/index.js"]
